_collections/_section_ios/usage.md
=> - Update Docs

_collections/_section_android/dailyRate.md, _collections/_section_android/getVehicles.md, _collections/_section_android/inpath.md, _collections/_section_android/inpathReservation.md, _collections/_section_android/standalone.md, _collections/_section_android/widget.md, _collections/_section_introduction/inpath.md, _collections/_section_introduction/prerequisites.md, _collections/_section_ios/apiQueryParams.md, _collections/_section_ios/dailyRate.md, _collections/_section_ios/getVehicles.md, _collections/_section_ios/inpath.md, _collections/_section_ios/inpathReservation.md, _collections/_section_ios/installation.md, _collections/_section_ios/standalone.md, _collections/_section_ios/widget.md, _collections/_section_release_notes/8.6.md, _collections/_section_release_notes/8.7.md
Includes:
- Updated for the getVehicles API
- Update for reservation aspect
- Update for payload aspect
- Updating iOS vehicles and Stand Alone API
- Updated iOS standalone and inpath usage
- Added CTPassenger into documentation
- Added reservation details description
=> Updates for v8.7 Release

_collections/_section_android/getVehicles.md, _collections/_section_android/standalone.md, _collections/_section_ios/getVehicles.md, _collections/_section_ios/installation.md, _collections/_section_ios/standalone.md, _collections/_section_release_notes/8.9.1.md, _collections/_section_release_notes/8.9.md
=> Release 8.9.1

_collections/_section_android/reservations.md, _collections/_section_ios/inpath.md, _collections/_section_ios/reservations.md, _collections/_section_ios/standalone.md, _collections/_section_release_notes/8.11.md
=> Release 8.11.0

_collections/_section_android/inpath.md, _collections/_section_android/standalone.md, _collections/_section_ios/installation.md, _collections/_section_release_notes2020/10.9.md
iOS: Updated iOS node version
Android: Added requestCode property explanation for Inpath and Standalone
=> Added draft Release notes for v10.9.0

_collections/_section_release_notes2020/11.1.md, _collections/_section_release_notes2021/11.2.md, _config.yml
* Add new 2021 section
* Added 11.2 initial release notes (to be completed)
=>  Release 11.2.0 notes

docs/StyleGuide/sdktheming.md, docs/StyleGuide/typography.md, docs/android/apis/recentSearches.md, docs/android/customisation/themes.md, docs/android/inpath/implementationSteps.md, docs/android/inpath/propertyDescriptions.md, docs/android/installation.md, docs/android/standalone/propertyDescriptions.md, docs/ios/apis/apiQueryParams.md, docs/ios/customisation/themes.md, docs/ios/inpath/propertyDescriptions.md, docs/ios/inpath/reservationProcess.md, docs/ios/standalone/propertyDescriptions.md, index.md
Just small changes mainly around punctuation.
=> Documentation overhaul review

docs/Release Notes/12.0.md, docs/android/standalone/implementationSteps.md
* add missing code on how to use the abandonment flow (pinned vehicle);
* add Android information on the release notes of 12.0.0;
=> - Update Android implementationSteps.md

docs/Release Notes/12.0.md
* add Android patch information (12.0.1);
=> - Update release notes 12.0

docs/android/standalone/reservationRetrieval.md
PTCN-1967
* add more detail about how to get the Reservation details after finish the booking flow;
* make it clear how to use the requestCode when starting the standalone flow and when get the result in the onActivityResult callback;
=> - Improve Android Reservation documentation

docs/Release Notes/12.5.1.md
* add a new version (patch) for Android
=> - Add 12.5.1 release note

docs/android/installation.md
* add documentation about how to enable Java 8+ API desugaring support if the app that consumes the SDK has its minimumSDK set to lower Android API than 26;
=> - Add step into installation section

docs/android/customisation.md, docs/android/migrate.md, docs/ios/migrate.md, index.md
* add 2 buttons in the home screen to take users to the migration documentation;
=> - Adding Migrate sections fro both platforms

.gitignore, docker-compose.yml, docs/APIs/androidAPIs/bestDailyRates.md, docs/APIs/androidAPIs/clearStorage.md, docs/APIs/androidAPIs/recentSearches.md, docs/APIs/androidAPIs/reservations.md, docs/APIs/androidAPIs/vehicles.md, docs/Release Notes/14.0.1.md, docs/android/customisation/darkMode.md, docs/android/customisation/settings.md, docs/android/customisation/supplierBenefits.md, docs/android/customisation/themes.md, docs/android/customisation/usp.md, docs/android/inpath/implementationSteps.md, docs/android/inpath/propertyDescriptions.md, docs/android/migrate.md, docs/android/standalone/implementationSteps.md, docs/android/standalone/propertyDescriptions.md, docs/android/standalone/reservationRetrieval.md, docs/react native/androidIntegration.md, index.md
* update Standalone, In Path, Customisation and Reactive Native section and sub-sections with new way of initialise the SDK;
=> - Update Android documentation

docs/flutter/flutter.md, docs/flutter/flutterandroidIntegration.md, docs/react native/androidIntegration.md, docs/react native/react-native.md, docs/releaseNotes.md, docs/styleGuide.md
=> Native 555 android flutter docs

docs/Release Notes/14.1.0.md
* add eco car feature description to the new functionality section;
=> - Add Release Notes 14.1.0

docs/Release Notes/14.4.0.md, docs/android/standalone/reservationRetrieval.md, docs/ios/standalone/reservationRetrieval.md
* update Android Integration -> Standalone -> Reservation Retrieval to include clientId in the ReservationDetails data class example;
=> - Add Release Notes 14.4.0

docs/android/standalone/implementationSteps.md
* add documentation explaining how to launch the SDK by using a deep link url;
=> - Add Android Deep Link documentation

docs/Release Notes/14.6.0.md
=> Add more 14.6 release notes

docs/Release Notes/14.10.0.md, docs/android/inpath/propertyDescriptions.md, docs/android/languages.md, docs/android/standalone/propertyDescriptions.md, docs/ios/inpath/implementationSteps.md, docs/ios/languages.md, docs/ios/standalone/implementationSteps.md
=> Release notes 14.10.0

docs/Release Notes/AndroidReleaseNotes/14.12.0.md, docs/Release Notes/AndroidReleaseNotes/14.13.0.md, docs/Release Notes/AndroidReleaseNotes/14.14.1.md, docs/Release Notes/iOSReleaseNotes/14.12.0.md, docs/Release Notes/iOSReleaseNotes/14.13.0.md, docs/Release Notes/iOSReleaseNotes/14.14.0.md
NATIVE-1202 - Release notes for 14.12/13/14
=> NATIVE-1202 - Release notes for 14.12/13/14

docs/Release Notes/AndroidReleaseNotes/15.7.0.md, docs/Release Notes/iOSReleaseNotes/15.7.0.md
=> Adding notes for 15.7.0
